"""Modification deck rajout de tags

Revision ID: 08934ccae6fa
Revises: c363a8b4f859
Create Date: 2025-11-12 18:56:30.607638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08934ccae6fa'
down_revision = 'c363a8b4f859'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag_deck',
    sa.Column('deck_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['deck_id'], ['deck.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('deck_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tag_deck')
    op.drop_table('tag')
    # ### end Alembic commands ###
